
package services;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "DBWSService", targetNamespace = "http://services", wsdlLocation = "http://localhost:8080/testi3/services/DBWS?wsdl")
public class DBWSService
    extends Service
{

    private final static URL DBWSSERVICE_WSDL_LOCATION;
    private final static WebServiceException DBWSSERVICE_EXCEPTION;
    private final static QName DBWSSERVICE_QNAME = new QName("http://services", "DBWSService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/testi3/services/DBWS?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        DBWSSERVICE_WSDL_LOCATION = url;
        DBWSSERVICE_EXCEPTION = e;
    }

    public DBWSService() {
        super(__getWsdlLocation(), DBWSSERVICE_QNAME);
    }

    public DBWSService(WebServiceFeature... features) {
        super(__getWsdlLocation(), DBWSSERVICE_QNAME, features);
    }

    public DBWSService(URL wsdlLocation) {
        super(wsdlLocation, DBWSSERVICE_QNAME);
    }

    public DBWSService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, DBWSSERVICE_QNAME, features);
    }

    public DBWSService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public DBWSService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns DBWS
     */
    @WebEndpoint(name = "DBWS")
    public DBWS getDBWS() {
        return super.getPort(new QName("http://services", "DBWS"), DBWS.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns DBWS
     */
    @WebEndpoint(name = "DBWS")
    public DBWS getDBWS(WebServiceFeature... features) {
        return super.getPort(new QName("http://services", "DBWS"), DBWS.class, features);
    }

    private static URL __getWsdlLocation() {
        if (DBWSSERVICE_EXCEPTION!= null) {
            throw DBWSSERVICE_EXCEPTION;
        }
        return DBWSSERVICE_WSDL_LOCATION;
    }

}
